### ISSUE TITLE
Problems with the twitter feeds

### ISSUE THREAD

**Issue by Sommerwiesel** [moson-mo/mnserver#3]
Cheers moson, it's me, the current "official unofficial hoster" of this cool little software.
I think twitter (probably following their rebrand and/or lockdown of their public APIs) broke something:

Nov 03 09:43:20 manjaro.news mnserver[1020]: 2023-11-03 - 09:43:20:        Getting news from twitter...
Nov 03 09:43:20 manjaro.news mnserver[1020]: 2023-11-03 - 09:43:20:        response status 404 Not Found: {"errors":[{"message":"Sorry, that page does not exist","code":34}]}

Or maybe the feed the software looks for doesn't exist anymore, I don't know, I don't use twitter.

Looking forward to your feedback,

Marvin

**Comment by moson-mo** [comment]
Hi Marvin,

Try to bump the dependencies to update the twitter scraper lib. Like:  `go get -u ./...`

However, I guess nowadays one needs a twitter account to access anything on that platform.  
Looking at the library it says:

![image](https://github.com/moson-mo/mnserver/assets/13588013/ca3d6bb8-41c9-4239-9af1-d66d70e58649)

I don't have a twitter/X so I can't work on this / fix it really. 🤷🏻

**Comment by Sommerwiesel** [comment]
Heyho,
Updating doesn't work, the API is locked-down, like the scraper says.
I think I'm just gonna leave it as-is (with the twitter feed broken).

Twitter (and many others) have started locking-down their APIs (like you said) and I neither have the time or money (if they ever start charging for requests too like reddit) required to keep using all these shitty proprietary services.

Fuck twitter, seriously :D
